inherit_from: .rubocop_todo.yml

require: rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'log/**/*'
    - 'db/**'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Documentation:
  Enabled: false
Rails:
  Enabled: true
